cms:
  url: https://api.simonjamesrowe.com
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  cloud:
    function:
      definition: consumeEvent
    stream:
      bindings:
        output:
          destination: ${namespace:LOCAL}_EVENTS
          producer:
            use-native-encoding: true
            partition-count: 1
        consumeEvent-in-0:
          destination: ${namespace:LOCAL}_EVENTS
          group: search-service
          consumer:
            batch-mode: true
            use-native-decoding: true
      kafka:
        binder:
          brokers: ${spring.kafka.bootstrap-servers}
          consumer-properties:
            max.poll.records: 50
          auto-add-partitions: true
          replication-factor: 1
        bindings:
          default:
            consumer:
              autoCommitOnError: false
              autoCommitOffset: true
              startOffset: earliest
              headerMode: raw
          consumeEvent-in-0:
            consumer:
              configuration:
                value.deserializer: com.simonjamesrowe.model.serialization.WebhookEventDeserializer
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          output:
            producer:
              configuration:
                value.serializer: com.simonjamesrowe.model.serialization.WebhookEventSerializer
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: com.simonjamesrowe.model

elasticsearch:
  index:
    blog: blog_${namespace:local}
    site: site_${namespace:local}
