cms:
  url: https://api.simonjamesrowe.com
spring:
  application:
    name: search-service
  jackson:
    serialization:
      write_dates_as_timestamps: false
  codec:
    max-in-memory-size: 10MB
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: com.simonjamesrowe.model
      group-id: search-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.simonjamesrowe.model.serialization.WebhookEventDeserializer
      max-poll-records: 20
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.simonjamesrowe.model.serialization.WebhookEventSerializer
  sleuth:
    messaging:
      kafka:
        enabled: false
  main:
    allow-bean-definition-overriding: true
  zipkin:
    sender:
      type: web
    service:
      name: ${spring.application.name}-${namespace:local}


elasticsearch:
  index:
    blog: blog_${namespace:local}
    site: site_${namespace:local}


